[project]
name = "dagster_dbt_sales_demo"
version = "0.1.0"
description = "Dagster partitioning demo for daily sales with dbt + Snowflake"
requires-python = ">=3.10"
dependencies = [
  "dagster",
  "dagster-webserver",
  "dagster-dbt",
  "dagster-cloud",              # ğŸ‘ˆ important new line
  "dbt-snowflake",
  "snowflake-connector-python",
]
